/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class ACharTipos extends PTipos
{
    private TCharSpecifier _charSpecifier_;

    public ACharTipos()
    {
        // Constructor
    }

    public ACharTipos(
        @SuppressWarnings("hiding") TCharSpecifier _charSpecifier_)
    {
        // Constructor
        setCharSpecifier(_charSpecifier_);

    }

    @Override
    public Object clone()
    {
        return new ACharTipos(
            cloneNode(this._charSpecifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACharTipos(this);
    }

    public TCharSpecifier getCharSpecifier()
    {
        return this._charSpecifier_;
    }

    public void setCharSpecifier(TCharSpecifier node)
    {
        if(this._charSpecifier_ != null)
        {
            this._charSpecifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._charSpecifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._charSpecifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._charSpecifier_ == child)
        {
            this._charSpecifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._charSpecifier_ == oldChild)
        {
            setCharSpecifier((TCharSpecifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
