/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AConjuntoBasic extends PBasic
{
    private PConjunto _conjunto_;

    public AConjuntoBasic()
    {
        // Constructor
    }

    public AConjuntoBasic(
        @SuppressWarnings("hiding") PConjunto _conjunto_)
    {
        // Constructor
        setConjunto(_conjunto_);

    }

    @Override
    public Object clone()
    {
        return new AConjuntoBasic(
            cloneNode(this._conjunto_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConjuntoBasic(this);
    }

    public PConjunto getConjunto()
    {
        return this._conjunto_;
    }

    public void setConjunto(PConjunto node)
    {
        if(this._conjunto_ != null)
        {
            this._conjunto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._conjunto_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._conjunto_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._conjunto_ == child)
        {
            this._conjunto_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._conjunto_ == oldChild)
        {
            setConjunto((PConjunto) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
