/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class ADecChar extends PChar
{
    private TCharDec _charDec_;

    public ADecChar()
    {
        // Constructor
    }

    public ADecChar(
        @SuppressWarnings("hiding") TCharDec _charDec_)
    {
        // Constructor
        setCharDec(_charDec_);

    }

    @Override
    public Object clone()
    {
        return new ADecChar(
            cloneNode(this._charDec_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecChar(this);
    }

    public TCharDec getCharDec()
    {
        return this._charDec_;
    }

    public void setCharDec(TCharDec node)
    {
        if(this._charDec_ != null)
        {
            this._charDec_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._charDec_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._charDec_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._charDec_ == child)
        {
            this._charDec_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._charDec_ == oldChild)
        {
            setCharDec((TCharDec) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
