/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class ADoubleTipos extends PTipos
{
    private TDoubleSpecifier _doubleSpecifier_;

    public ADoubleTipos()
    {
        // Constructor
    }

    public ADoubleTipos(
        @SuppressWarnings("hiding") TDoubleSpecifier _doubleSpecifier_)
    {
        // Constructor
        setDoubleSpecifier(_doubleSpecifier_);

    }

    @Override
    public Object clone()
    {
        return new ADoubleTipos(
            cloneNode(this._doubleSpecifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADoubleTipos(this);
    }

    public TDoubleSpecifier getDoubleSpecifier()
    {
        return this._doubleSpecifier_;
    }

    public void setDoubleSpecifier(TDoubleSpecifier node)
    {
        if(this._doubleSpecifier_ != null)
        {
            this._doubleSpecifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._doubleSpecifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._doubleSpecifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._doubleSpecifier_ == child)
        {
            this._doubleSpecifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._doubleSpecifier_ == oldChild)
        {
            setDoubleSpecifier((TDoubleSpecifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
