/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AEstrelaOpUn extends POpUn
{
    private TEstrela _estrela_;

    public AEstrelaOpUn()
    {
        // Constructor
    }

    public AEstrelaOpUn(
        @SuppressWarnings("hiding") TEstrela _estrela_)
    {
        // Constructor
        setEstrela(_estrela_);

    }

    @Override
    public Object clone()
    {
        return new AEstrelaOpUn(
            cloneNode(this._estrela_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEstrelaOpUn(this);
    }

    public TEstrela getEstrela()
    {
        return this._estrela_;
    }

    public void setEstrela(TEstrela node)
    {
        if(this._estrela_ != null)
        {
            this._estrela_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._estrela_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._estrela_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._estrela_ == child)
        {
            this._estrela_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._estrela_ == oldChild)
        {
            setEstrela((TEstrela) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
