/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AExprRegTail extends PExprRegTail
{
    private TBarra _barra_;
    private PConcat _concat_;

    public AExprRegTail()
    {
        // Constructor
    }

    public AExprRegTail(
        @SuppressWarnings("hiding") TBarra _barra_,
        @SuppressWarnings("hiding") PConcat _concat_)
    {
        // Constructor
        setBarra(_barra_);

        setConcat(_concat_);

    }

    @Override
    public Object clone()
    {
        return new AExprRegTail(
            cloneNode(this._barra_),
            cloneNode(this._concat_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprRegTail(this);
    }

    public TBarra getBarra()
    {
        return this._barra_;
    }

    public void setBarra(TBarra node)
    {
        if(this._barra_ != null)
        {
            this._barra_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._barra_ = node;
    }

    public PConcat getConcat()
    {
        return this._concat_;
    }

    public void setConcat(PConcat node)
    {
        if(this._concat_ != null)
        {
            this._concat_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._concat_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._barra_)
            + toString(this._concat_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._barra_ == child)
        {
            this._barra_ = null;
            return;
        }

        if(this._concat_ == child)
        {
            this._concat_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._barra_ == oldChild)
        {
            setBarra((TBarra) newChild);
            return;
        }

        if(this._concat_ == oldChild)
        {
            setConcat((PConcat) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
