/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AExprUn extends PExprUn
{
    private PBasic _basic_;
    private POpUn _opUn_;

    public AExprUn()
    {
        // Constructor
    }

    public AExprUn(
        @SuppressWarnings("hiding") PBasic _basic_,
        @SuppressWarnings("hiding") POpUn _opUn_)
    {
        // Constructor
        setBasic(_basic_);

        setOpUn(_opUn_);

    }

    @Override
    public Object clone()
    {
        return new AExprUn(
            cloneNode(this._basic_),
            cloneNode(this._opUn_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprUn(this);
    }

    public PBasic getBasic()
    {
        return this._basic_;
    }

    public void setBasic(PBasic node)
    {
        if(this._basic_ != null)
        {
            this._basic_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._basic_ = node;
    }

    public POpUn getOpUn()
    {
        return this._opUn_;
    }

    public void setOpUn(POpUn node)
    {
        if(this._opUn_ != null)
        {
            this._opUn_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opUn_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._basic_)
            + toString(this._opUn_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._basic_ == child)
        {
            this._basic_ = null;
            return;
        }

        if(this._opUn_ == child)
        {
            this._opUn_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._basic_ == oldChild)
        {
            setBasic((PBasic) newChild);
            return;
        }

        if(this._opUn_ == oldChild)
        {
            setOpUn((POpUn) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
