/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AGrammarStart extends PStart
{
    private PGrammar _grammar_;

    public AGrammarStart()
    {
        // Constructor
    }

    public AGrammarStart(
        @SuppressWarnings("hiding") PGrammar _grammar_)
    {
        // Constructor
        setGrammar(_grammar_);

    }

    @Override
    public Object clone()
    {
        return new AGrammarStart(
            cloneNode(this._grammar_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGrammarStart(this);
    }

    public PGrammar getGrammar()
    {
        return this._grammar_;
    }

    public void setGrammar(PGrammar node)
    {
        if(this._grammar_ != null)
        {
            this._grammar_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._grammar_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._grammar_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._grammar_ == child)
        {
            this._grammar_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._grammar_ == oldChild)
        {
            setGrammar((PGrammar) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
