/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AHexChar extends PChar
{
    private TCharHexa _charHexa_;

    public AHexChar()
    {
        // Constructor
    }

    public AHexChar(
        @SuppressWarnings("hiding") TCharHexa _charHexa_)
    {
        // Constructor
        setCharHexa(_charHexa_);

    }

    @Override
    public Object clone()
    {
        return new AHexChar(
            cloneNode(this._charHexa_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAHexChar(this);
    }

    public TCharHexa getCharHexa()
    {
        return this._charHexa_;
    }

    public void setCharHexa(TCharHexa node)
    {
        if(this._charHexa_ != null)
        {
            this._charHexa_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._charHexa_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._charHexa_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._charHexa_ == child)
        {
            this._charHexa_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._charHexa_ == oldChild)
        {
            setCharHexa((TCharHexa) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
