/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AIntervaloConjunto extends PConjunto
{
    private TColEsq _colEsq_;
    private PChar _left_;
    private TDDot _dDot_;
    private PChar _right_;
    private TColDir _colDir_;

    public AIntervaloConjunto()
    {
        // Constructor
    }

    public AIntervaloConjunto(
        @SuppressWarnings("hiding") TColEsq _colEsq_,
        @SuppressWarnings("hiding") PChar _left_,
        @SuppressWarnings("hiding") TDDot _dDot_,
        @SuppressWarnings("hiding") PChar _right_,
        @SuppressWarnings("hiding") TColDir _colDir_)
    {
        // Constructor
        setColEsq(_colEsq_);

        setLeft(_left_);

        setDDot(_dDot_);

        setRight(_right_);

        setColDir(_colDir_);

    }

    @Override
    public Object clone()
    {
        return new AIntervaloConjunto(
            cloneNode(this._colEsq_),
            cloneNode(this._left_),
            cloneNode(this._dDot_),
            cloneNode(this._right_),
            cloneNode(this._colDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntervaloConjunto(this);
    }

    public TColEsq getColEsq()
    {
        return this._colEsq_;
    }

    public void setColEsq(TColEsq node)
    {
        if(this._colEsq_ != null)
        {
            this._colEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colEsq_ = node;
    }

    public PChar getLeft()
    {
        return this._left_;
    }

    public void setLeft(PChar node)
    {
        if(this._left_ != null)
        {
            this._left_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._left_ = node;
    }

    public TDDot getDDot()
    {
        return this._dDot_;
    }

    public void setDDot(TDDot node)
    {
        if(this._dDot_ != null)
        {
            this._dDot_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._dDot_ = node;
    }

    public PChar getRight()
    {
        return this._right_;
    }

    public void setRight(PChar node)
    {
        if(this._right_ != null)
        {
            this._right_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._right_ = node;
    }

    public TColDir getColDir()
    {
        return this._colDir_;
    }

    public void setColDir(TColDir node)
    {
        if(this._colDir_ != null)
        {
            this._colDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._colDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._colEsq_)
            + toString(this._left_)
            + toString(this._dDot_)
            + toString(this._right_)
            + toString(this._colDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._colEsq_ == child)
        {
            this._colEsq_ = null;
            return;
        }

        if(this._left_ == child)
        {
            this._left_ = null;
            return;
        }

        if(this._dDot_ == child)
        {
            this._dDot_ = null;
            return;
        }

        if(this._right_ == child)
        {
            this._right_ = null;
            return;
        }

        if(this._colDir_ == child)
        {
            this._colDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._colEsq_ == oldChild)
        {
            setColEsq((TColEsq) newChild);
            return;
        }

        if(this._left_ == oldChild)
        {
            setLeft((PChar) newChild);
            return;
        }

        if(this._dDot_ == oldChild)
        {
            setDDot((TDDot) newChild);
            return;
        }

        if(this._right_ == oldChild)
        {
            setRight((PChar) newChild);
            return;
        }

        if(this._colDir_ == oldChild)
        {
            setColDir((TColDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
