/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AIntTipos extends PTipos
{
    private TIntSpecifier _intSpecifier_;

    public AIntTipos()
    {
        // Constructor
    }

    public AIntTipos(
        @SuppressWarnings("hiding") TIntSpecifier _intSpecifier_)
    {
        // Constructor
        setIntSpecifier(_intSpecifier_);

    }

    @Override
    public Object clone()
    {
        return new AIntTipos(
            cloneNode(this._intSpecifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIntTipos(this);
    }

    public TIntSpecifier getIntSpecifier()
    {
        return this._intSpecifier_;
    }

    public void setIntSpecifier(TIntSpecifier node)
    {
        if(this._intSpecifier_ != null)
        {
            this._intSpecifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._intSpecifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._intSpecifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._intSpecifier_ == child)
        {
            this._intSpecifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._intSpecifier_ == oldChild)
        {
            setIntSpecifier((TIntSpecifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
