/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AStateListTail extends PStateListTail
{
    private TVirgula _virgula_;
    private TId _id_;
    private PTransition _transition_;

    public AStateListTail()
    {
        // Constructor
    }

    public AStateListTail(
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PTransition _transition_)
    {
        // Constructor
        setVirgula(_virgula_);

        setId(_id_);

        setTransition(_transition_);

    }

    @Override
    public Object clone()
    {
        return new AStateListTail(
            cloneNode(this._virgula_),
            cloneNode(this._id_),
            cloneNode(this._transition_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStateListTail(this);
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PTransition getTransition()
    {
        return this._transition_;
    }

    public void setTransition(PTransition node)
    {
        if(this._transition_ != null)
        {
            this._transition_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._transition_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._virgula_)
            + toString(this._id_)
            + toString(this._transition_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._transition_ == child)
        {
            this._transition_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._transition_ == oldChild)
        {
            setTransition((PTransition) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
