/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class AStringTipos extends PTipos
{
    private TStringSpecifier _stringSpecifier_;

    public AStringTipos()
    {
        // Constructor
    }

    public AStringTipos(
        @SuppressWarnings("hiding") TStringSpecifier _stringSpecifier_)
    {
        // Constructor
        setStringSpecifier(_stringSpecifier_);

    }

    @Override
    public Object clone()
    {
        return new AStringTipos(
            cloneNode(this._stringSpecifier_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStringTipos(this);
    }

    public TStringSpecifier getStringSpecifier()
    {
        return this._stringSpecifier_;
    }

    public void setStringSpecifier(TStringSpecifier node)
    {
        if(this._stringSpecifier_ != null)
        {
            this._stringSpecifier_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._stringSpecifier_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._stringSpecifier_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._stringSpecifier_ == child)
        {
            this._stringSpecifier_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._stringSpecifier_ == oldChild)
        {
            setStringSpecifier((TStringSpecifier) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
