/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class ATransition extends PTransition
{
    private TSetaDir _setaDir_;
    private TId _id_;

    public ATransition()
    {
        // Constructor
    }

    public ATransition(
        @SuppressWarnings("hiding") TSetaDir _setaDir_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setSetaDir(_setaDir_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new ATransition(
            cloneNode(this._setaDir_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATransition(this);
    }

    public TSetaDir getSetaDir()
    {
        return this._setaDir_;
    }

    public void setSetaDir(TSetaDir node)
    {
        if(this._setaDir_ != null)
        {
            this._setaDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._setaDir_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._setaDir_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._setaDir_ == child)
        {
            this._setaDir_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._setaDir_ == oldChild)
        {
            setSetaDir((TSetaDir) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
