/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class TCharSpecifier extends Token
{
    public TCharSpecifier()
    {
        super.setText("Char");
    }

    public TCharSpecifier(int line, int pos)
    {
        super.setText("Char");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TCharSpecifier(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTCharSpecifier(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TCharSpecifier text.");
    }
}
