/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class TDivint extends Token
{
    public TDivint()
    {
        super.setText("//");
    }

    public TDivint(int line, int pos)
    {
        super.setText("//");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDivint(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDivint(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDivint text.");
    }
}
