/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class TDivEq extends Token
{
    public TDivEq()
    {
        super.setText("/=");
    }

    public TDivEq(int line, int pos)
    {
        super.setText("/=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TDivEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTDivEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TDivEq text.");
    }
}
