/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class TModEq extends Token
{
    public TModEq()
    {
        super.setText("%=");
    }

    public TModEq(int line, int pos)
    {
        super.setText("%=");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TModEq(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTModEq(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TModEq text.");
    }
}
