/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class TSSlash extends Token
{
    public TSSlash()
    {
        super.setText("//");
    }

    public TSSlash(int line, int pos)
    {
        super.setText("//");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TSSlash(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTSSlash(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TSSlash text.");
    }
}
