/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class TStringSpecifier extends Token
{
    public TStringSpecifier()
    {
        super.setText("String");
    }

    public TStringSpecifier(int line, int pos)
    {
        super.setText("String");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TStringSpecifier(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTStringSpecifier(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TStringSpecifier text.");
    }
}
