/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.node;

import curtain.analysis.*;

@SuppressWarnings("nls")
public final class TTypedef extends Token
{
    public TTypedef()
    {
        super.setText("typedef");
    }

    public TTypedef(int line, int pos)
    {
        super.setText("typedef");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TTypedef(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTTypedef(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TTypedef text.");
    }
}
