/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.parser;

import curtain.node.*;
import curtain.analysis.*;

class TokenIndex extends AnalysisAdapter
{
    int index;

    @Override
    public void caseTPkgId(@SuppressWarnings("unused") TPkgId node)
    {
        this.index = 0;
    }

    @Override
    public void caseTPackage(@SuppressWarnings("unused") TPackage node)
    {
        this.index = 1;
    }

    @Override
    public void caseTStates(@SuppressWarnings("unused") TStates node)
    {
        this.index = 2;
    }

    @Override
    public void caseTHelpers(@SuppressWarnings("unused") THelpers node)
    {
        this.index = 3;
    }

    @Override
    public void caseTTokens(@SuppressWarnings("unused") TTokens node)
    {
        this.index = 4;
    }

    @Override
    public void caseTIgnored(@SuppressWarnings("unused") TIgnored node)
    {
        this.index = 5;
    }

    @Override
    public void caseTProductions(@SuppressWarnings("unused") TProductions node)
    {
        this.index = 6;
    }

    @Override
    public void caseTTokenSpecifier(@SuppressWarnings("unused") TTokenSpecifier node)
    {
        this.index = 7;
    }

    @Override
    public void caseTProductionSpceifier(@SuppressWarnings("unused") TProductionSpceifier node)
    {
        this.index = 8;
    }

    @Override
    public void caseTDot(@SuppressWarnings("unused") TDot node)
    {
        this.index = 9;
    }

    @Override
    public void caseTDDot(@SuppressWarnings("unused") TDDot node)
    {
        this.index = 10;
    }

    @Override
    public void caseTSemicolon(@SuppressWarnings("unused") TSemicolon node)
    {
        this.index = 11;
    }

    @Override
    public void caseTIgualdade(@SuppressWarnings("unused") TIgualdade node)
    {
        this.index = 12;
    }

    @Override
    public void caseTColEsq(@SuppressWarnings("unused") TColEsq node)
    {
        this.index = 13;
    }

    @Override
    public void caseTColDir(@SuppressWarnings("unused") TColDir node)
    {
        this.index = 14;
    }

    @Override
    public void caseTParEsq(@SuppressWarnings("unused") TParEsq node)
    {
        this.index = 15;
    }

    @Override
    public void caseTParDir(@SuppressWarnings("unused") TParDir node)
    {
        this.index = 16;
    }

    @Override
    public void caseTChaveEsq(@SuppressWarnings("unused") TChaveEsq node)
    {
        this.index = 17;
    }

    @Override
    public void caseTChaveDir(@SuppressWarnings("unused") TChaveDir node)
    {
        this.index = 18;
    }

    @Override
    public void caseTMais(@SuppressWarnings("unused") TMais node)
    {
        this.index = 19;
    }

    @Override
    public void caseTMenos(@SuppressWarnings("unused") TMenos node)
    {
        this.index = 20;
    }

    @Override
    public void caseTQMark(@SuppressWarnings("unused") TQMark node)
    {
        this.index = 21;
    }

    @Override
    public void caseTEstrela(@SuppressWarnings("unused") TEstrela node)
    {
        this.index = 22;
    }

    @Override
    public void caseTBarra(@SuppressWarnings("unused") TBarra node)
    {
        this.index = 23;
    }

    @Override
    public void caseTVirgula(@SuppressWarnings("unused") TVirgula node)
    {
        this.index = 24;
    }

    @Override
    public void caseTSlash(@SuppressWarnings("unused") TSlash node)
    {
        this.index = 25;
    }

    @Override
    public void caseTSSlash(@SuppressWarnings("unused") TSSlash node)
    {
        this.index = 26;
    }

    @Override
    public void caseTMod(@SuppressWarnings("unused") TMod node)
    {
        this.index = 27;
    }

    @Override
    public void caseTSetaDir(@SuppressWarnings("unused") TSetaDir node)
    {
        this.index = 28;
    }

    @Override
    public void caseTColon(@SuppressWarnings("unused") TColon node)
    {
        this.index = 29;
    }

    @Override
    public void caseTId(@SuppressWarnings("unused") TId node)
    {
        this.index = 30;
    }

    @Override
    public void caseTChar(@SuppressWarnings("unused") TChar node)
    {
        this.index = 31;
    }

    @Override
    public void caseTCharDec(@SuppressWarnings("unused") TCharDec node)
    {
        this.index = 32;
    }

    @Override
    public void caseTCharHexa(@SuppressWarnings("unused") TCharHexa node)
    {
        this.index = 33;
    }

    @Override
    public void caseTString(@SuppressWarnings("unused") TString node)
    {
        this.index = 34;
    }

    @Override
    public void caseEOF(@SuppressWarnings("unused") EOF node)
    {
        this.index = 35;
    }
}
