/* This file was generated by SableCC (http://www.sablecc.org/). */

package curtain.analysis;

import curtain.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAFactorExpr(AFactorExpr node);
    void caseASomaExpr(ASomaExpr node);
    void caseAMenosExpr(AMenosExpr node);
    void caseATermFactor(ATermFactor node);
    void caseAMultFactor(AMultFactor node);
    void caseADivFactor(ADivFactor node);
    void caseAModFactor(AModFactor node);
    void caseANumeroTerm(ANumeroTerm node);
    void caseAExprTerm(AExprTerm node);

    void caseTNumero(TNumero node);
    void caseTSoma(TSoma node);
    void caseTMenos(TMenos node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTDivint(TDivint node);
    void caseTMod(TMod node);
    void caseTParEsq(TParEsq node);
    void caseTParDir(TParDir node);
    void caseTVazio(TVazio node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
